services:
  postgres:
    image: postgres:16-alpine
    container_name: invoice_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: invoice_app
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_password
    ports:
      - "5432:5432"
    volumes:
      - invoice_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoice_app"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: invoice_backend
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_NAME: InvoiceTestAssignment
      APP_ENV: local
      APP_KEY: base64:YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      LOG_CHANNEL: stack
      LOG_LEVEL: debug

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: invoice_app
      DB_USERNAME: invoice_user
      DB_PASSWORD: invoice_password

      SESSION_DRIVER: file
      CACHE_STORE: database
      QUEUE_CONNECTION: database
    command: >
      sh -lc "
        composer install &&
        php artisan config:clear &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  frontend:
    build:
      context: ./frontend
    container_name: invoice_frontend
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_BASE_URL: http://localhost:8000/api
    command: >
      sh -lc "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 3000
      "

volumes:
  invoice_postgres_data:
